apiVersion: v2
name: karpenter-crd
description: A Helm chart for Karpenter Custom Resource Definitions (CRDs).
type: application
version: 1.0.9-build05
appVersion: 1.0.9-build05
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
home: https://github.com/zoom/karpenter-oci/
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
sources:
  - https://github.com/zoom/karpenter-oci/
